/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EditCarRouteImport } from './routes/edit-car'
import { Route as AddCarRouteImport } from './routes/add-car'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EditCarIdRouteImport } from './routes/edit-car/$id'
import { Route as CarIdRouteImport } from './routes/car/$id'

const EditCarRoute = EditCarRouteImport.update({
  id: '/edit-car',
  path: '/edit-car',
  getParentRoute: () => rootRouteImport,
} as any)
const AddCarRoute = AddCarRouteImport.update({
  id: '/add-car',
  path: '/add-car',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditCarIdRoute = EditCarIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EditCarRoute,
} as any)
const CarIdRoute = CarIdRouteImport.update({
  id: '/car/$id',
  path: '/car/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-car': typeof AddCarRoute
  '/edit-car': typeof EditCarRouteWithChildren
  '/car/$id': typeof CarIdRoute
  '/edit-car/$id': typeof EditCarIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-car': typeof AddCarRoute
  '/edit-car': typeof EditCarRouteWithChildren
  '/car/$id': typeof CarIdRoute
  '/edit-car/$id': typeof EditCarIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-car': typeof AddCarRoute
  '/edit-car': typeof EditCarRouteWithChildren
  '/car/$id': typeof CarIdRoute
  '/edit-car/$id': typeof EditCarIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/add-car' | '/edit-car' | '/car/$id' | '/edit-car/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/add-car' | '/edit-car' | '/car/$id' | '/edit-car/$id'
  id: '__root__' | '/' | '/add-car' | '/edit-car' | '/car/$id' | '/edit-car/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddCarRoute: typeof AddCarRoute
  EditCarRoute: typeof EditCarRouteWithChildren
  CarIdRoute: typeof CarIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/edit-car': {
      id: '/edit-car'
      path: '/edit-car'
      fullPath: '/edit-car'
      preLoaderRoute: typeof EditCarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-car': {
      id: '/add-car'
      path: '/add-car'
      fullPath: '/add-car'
      preLoaderRoute: typeof AddCarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-car/$id': {
      id: '/edit-car/$id'
      path: '/$id'
      fullPath: '/edit-car/$id'
      preLoaderRoute: typeof EditCarIdRouteImport
      parentRoute: typeof EditCarRoute
    }
    '/car/$id': {
      id: '/car/$id'
      path: '/car/$id'
      fullPath: '/car/$id'
      preLoaderRoute: typeof CarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EditCarRouteChildren {
  EditCarIdRoute: typeof EditCarIdRoute
}

const EditCarRouteChildren: EditCarRouteChildren = {
  EditCarIdRoute: EditCarIdRoute,
}

const EditCarRouteWithChildren =
  EditCarRoute._addFileChildren(EditCarRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddCarRoute: AddCarRoute,
  EditCarRoute: EditCarRouteWithChildren,
  CarIdRoute: CarIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
